# -*- coding: utf-8 -*-
"""Crew AI agent (LC&LG)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-fL_jU5_romx849fQx6fTWW-v5Z7AXk

#  AI **AGENT**
"""



!pip install -qU "langchain[google-genai]"

!pip install -qU langchain-google-genai

from google.colab import userdata
API_KEY = userdata.get('GOOGLE_API_KEY')

!pip install crewai

from crewai import Agent, Task, Crew, LLM

agent = Agent(
  role = "Motivational Speaker",
  goal = "Create an inspirational LinkedIn post for job seekers",
  backstory = "An experienced career mentor who inspires others through writing.",
  llm = LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
  #llm=LLM(model="gemini/gemini-gemini-2.5-pro", api_key=API_KEY)
)

task = Task(
    description = "Write a short LinkedIn post to motivate job seekers",
    expected_output = "Clean and humanised Linkedin post",
    agent = agent
)

crew = Crew(
    agents = [agent],
    tasks = [task]
)

print(crew.kickoff())

"""# Custom Input.."""

from crewai import Agent, Task, Crew, LLM

agent1 = Agent(
  role = "Motivational Speaker",
  goal = "Create an inspirational LinkedIn post for job seekers",
  backstory = "An experienced career mentor who inspires others through writing.",
  llm = LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
)

task1 = Task(
    description = "Write a short LinkedIn post to motivate job seekers on topic = {topic}",
    expected_output = "Clean and humanised Linkedin post",
    agent = agent1
)

crew1 = Crew(
    agents = [agent1],
    tasks = [task1]
)

print(crew1.kickoff(inputs={"topic": "Your help in developing India"}))

"""# Multi Agent..."""

!pip install 'crewai[tools]'

!pip install firecrawl-py

from google.colab import userdata
API_KEY = userdata.get('GOOGLE_API_KEY')

from crewai import Agent, Task, Crew, LLM
import time
import os

os.environ.pop("GEMINI_API_KEY", None)

researcher = Agent(
    role="Current Affairs Researcher",
    goal="List the top 5 most relevant current global news topics.",
    backstory="A well-informed researcher with access to up-to-date world events.",
    llm=LLM(model="gemini/gemini-2.5-flash-lite", api_key=API_KEY)
)


summarizer = Agent(
    role="Note Maker",
    goal="Convert research into short bullet points.",
    backstory="An expert at simplifying complex information.",
    llm=LLM(model="gemini/gemini-2.5-flash-lite", api_key=API_KEY)
)

task1 = Task(
    description="List the top 5 global news topics currently being discussed worldwide.",
    expected_output="Top 5 topics with 1-line explanation each.",
    agent=researcher
)

task2 = Task(
    description="Summarize those 5 topics clearly and concisely for a daily news digest.",
    expected_output="Concise bullet-point summaries.",
    agent=summarizer
)

current_affairs_crew = Crew(
    agents=[researcher, summarizer],
    tasks=[task1, task2],
    process="sequential"
)

for attempt in range(3):
    try:
        print(f" Attempt {attempt+1}: Running current_affairs_crew...")
        result = current_affairs_crew.kickoff()
        print("FINAL OUTPUT:", result)
        break
    except Exception as e:
        print(f" Attempt {attempt+1} failed: {e}")
        time.sleep(5)

"""# Human in the loop"""

from crewai import Agent, Task, Crew, LLM

per_agent = Agent(
    role="Friendly Motivator",
    goal="Encourage users with personalized messages",
    backstory="An assistant that learns users' names and motivates them kindly.",
    llm=LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
)


user_name = input("Hi What's your name...")


task1 = Task(
    description=f"The user's name is {user_name}. Remember it for future messages.",
    expected_output="Remember given user name",
    agent=per_agent
)


task2 = Task(
    description="Using the user's name from memory, write a short motivational message.",
    expected_output="Personalized motivational message with the given name",
    agent=per_agent
)


crew = Crew(
    agents=[per_agent],
    tasks=[task1, task2],
    process="sequential",
    verbose=True
)

output = crew.kickoff()
print(output)

"""# Crew **AI agent** (LC&LG)

### *AI Research Summary Generator*
"""



!pip install -qU "langchain[google-genai]"
!pip install -qU langchain-google-genai

!pip install -qU crewai

!pip install -qU "crewai[tools]"

!pip install -qU firecrawl-py

from google.colab import userdata
from crewai import Agent, Task, Crew, LLM, Process

from crewai_tools import FirecrawlSearchTool
from langchain_google_genai import GoogleGenerativeAIEmbeddings





API_KEY = userdata.get('GOOGLE_API_KEY')

if not API_KEY:
    raise ValueError("Missing API key. Please set your GOOGLE_API_KEY in Colab > ‘User data’ section.")
else:
    print("API key loaded successfully!")

topic = input("Enter a topic you want the AI to research and summarize: ")
print('Topic selected' ,'{topic}')

researcher = Agent(
    role="Research Analyst",
    goal="Gather accurate and recent information on a given topic.",
    backstory="An expert in web research, data synthesis, and factual accuracy.",
    tools=[],
    verbose=True,
    llm=LLM(model="gemini/gemini-2.0-flash", api_key=API_KEY)
    #llm = LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
)


summarizer = Agent(
    role="Summary Expert",
    goal="Condense research into 4–6 clear, useful bullet points.",
    backstory="A detail-oriented professional who simplifies complex research.",
    verbose=True,
    #llm = LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
    llm=LLM(model="gemini/gemini-2.0-flash", api_key=API_KEY)
)


writer = Agent(
    role="Content Writer",
    goal="Write a short, professional research summary post for LinkedIn/blog.",
    backstory="An experienced content creator who writes with clarity and engagement.",
    verbose=True,
    #llm = LLM(model="gemini/gemini-2.5-flash-lite",api_key=API_KEY)
    llm=LLM(model="gemini/gemini-2.0-flash", api_key=API_KEY)
)

task1 = Task(
    description=f"Research and gather the latest details, facts, and trends about '{topic}'.",
    expected_output="Detailed notes and insights about the topic.",
    agent=researcher
)


task2 = Task(
    description="Summarize the research into concise, factual, readable bullet points.",
    expected_output="A clear 4–6 point summary of the topic.",
    agent=summarizer
)


task3 = Task(
    description="Using the summarized data, write a short research summary post suitable for LinkedIn or professional sharing.",
    expected_output="A polished, 5–8 sentence summary post.",
    agent=writer
)



research_summary_crew = Crew(
    agents=[researcher, summarizer, writer],
    tasks=[task1, task2, task3],
    process=Process.sequential,
    memory=False,
    verbose=True
)

print("Running AI automation process...")
final_output = research_summary_crew.kickoff()

print("FINAL RESEARCH SUMMARY POST: ")

try:
    if hasattr(final_output, "output"):
        text_result = final_output.output
    elif hasattr(final_output, "raw"):
        text_result = final_output.raw
    elif hasattr(final_output, "result"):
        text_result = final_output.result
    elif hasattr(final_output, "tasks_output"):
        text_result = str(final_output.tasks_output)
    else:
        text_result = str(final_output)
except Exception as e:
    text_result = "Could not extract output: " + str(e)

print(text_result)


filename = "research summary" + topic.replace(" ","_") + ".txt"
with open(filename, "w") as f:
    f.write(text_result)

print("Saved your summary post as '" + filename + "' in Colab files.")